### ISSUE TITLE
Poison depedency

### ISSUE THREAD

**Issue by happysalada** [scrogson/oauth2#114]
You have a dependency on Poison.
Probably up until now, since Phoenix was using poison, it was working fine. The new Phoenix use Jason. So you will either need to specify the Poison dependency or switch to using Jason.

**Comment by scrogson** [comment]
Hi @happysalada,

This library only depends on `Poison` for tests, but it does set up the JSON serializer to use `Poison` by default and requires users to pull it in as a dependency.

I have this PR: https://github.com/scrogson/oauth2/pull/92 (which is over 1 year old) which changes the way serializers are registered.

I'll probably consider using `Jason` instead of `Poison` before I get around to pulling the trigger on merging it.

Thanks
