### ISSUE TITLE
Adding OAuth2 Token Introspection

### ISSUE THREAD

**Issue by RyanSiu1995** [scrogson/oauth2#126]
Does it sound good to add token introspection into the library? This makes the library not to restrict in serving as the OAuth client. It can also be a resource provider.
Any ideas?

Ref: [https://tools.ietf.org/html/rfc7662](https://tools.ietf.org/html/rfc7662)

**Comment by scrogson** [comment]
Hi @RyanSiu1995,

So far, I've only been interested in supporting the base OAuth2 spec in this library. With that said, I'm open to seeing some proposals to what changes would be needed in order to support this.

I don't have much time or interest in doing this work myself, but if you're up for it, I'd be open to hearing what you have in mind.

**Comment by RyanSiu1995** [comment]
Hi @scrogson, 
I just want to have a simple extension about introspection first, like this.
```elixir
@spec is_valid?(access_token, response_handler) :: boolean
def is_valid?(access_token, fn) do
  # TODO
end
```
The function just first checks the access token with authorization party. Then, the user can use his own customized function to handle the response. Like some responses from the authorization party may lead to the failure of authentication. 
It may be a simple function for the moment being first. All in all, I am new to participate open-source project and elixir.
