### ISSUE TITLE
AccessToken in URL param instead of Authentication header

### ISSUE THREAD

**Issue by optikfluffel** [scrogson/oauth2#28]
Hi, I'm playing around with the Soundcloud API and when doing a request they want me to put the `AccessToken` into an URL param like this `https://api.soundcloud.com/me?oauth_token=A_VALID_TOKEN` instead of putting it into the `Authorization` header as a Bearer token.
Could you give me a hint on what's the easiest way to get this going with your library?

Right now I'm simply doing this little, dirty workaround:
```elixir
def get!(token, url) do
  access_token = Map.get(token, :access_token)
  url_with_token = url <> "?oauth_token=" <> access_token
  OAuth2.AccessToken.get!(token, url_with_token)
end
```

Thanks :)

**Comment by scrogson** [comment]
@optikfluffel currently, what you are doing is the only solution. I will fix this though. Right now, I've almost nearly rewritten `httpoison` inside this lib so that I could automatically parse the the body based on the `content-type` and `accept` headers. So I left out the fact that you can pass in `:params` into the `opts` for the `request` function.

I'll try to get this improved soon.

**Comment by optikfluffel** [comment]
![Thank you](https://cloud.githubusercontent.com/assets/379915/9463348/6ed1b3f4-4b1c-11e5-9e98-d22e98cfe900.jpg)

**Comment by scrogson** [comment]
@optikfluffel this should be fixed in master. Can you try it out and let me know?

**Comment by scrogson** [comment]
@optikfluffel confirmed: https://github.com/scrogson/oauth2/commit/bc5f8dcd4669740aac75d0dbffaa373dd70375eb
