### ISSUE TITLE
Any chance to rename the application?

### ISSUE THREAD

**Issue by yrashk** [scrogson/oauth2#4]
Hi,

Any chance to rename the application to avoid the clash with https://github.com/kivra/oauth2? I want to use both apps!

Thanks :)

**Comment by scrogson** [comment]
Would `:o_auth2` suffice?

**Comment by yrashk** [comment]
That works, too

On Tuesday, January 20, 2015, Sonny Scroggin <notifications@github.com>
wrote:

> Would :o_auth2 suffice?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scrogson/oauth2/issues/4#issuecomment-70534977>.
>


-- 
Y.
My company is hiring: https://trustatom.com/jobs

**Comment by scrogson** [comment]
Hey @yrashk I've decided against renaming as it's already been on `hex` for many months now. Let me know what features `kivra/oauth2` provides that are missing here and I'll see if I can work it in.

I've changed the API a bit since this issue was first created and I plan on making more improvements.

**Comment by deadtrickster** [comment]
@scrogson is this final?
