### ISSUE TITLE
Not sending client_secret when getting token

### ISSUE THREAD

**Issue by abadongutierrez** [scrogson/oauth2#97]
I'm using oauth2 trying to connect to a Slack App. When get_token it is failing with:

"{\"ok\":false,\"error\":\"bad_client_secret\"}"

because Slack Access Token URL accepts the client_secret as param but oauth2 is not sending it.

A simple hack is to add the client_secret as param to the get_token function but is that correct?

**Comment by scrogson** [comment]
Hi there @abadongutierrez,

This question has come up a lot. The short answer is that the `client_secret` is not mentioned as a required field in the OAuth2 spec for authorization code flow. Because of that, it is not supplied by the `OAuth2.Strategies.AuthCode` strategy. You can always add it manually by using `OAuth2.Client.put_param`.

**Comment by jeremyjh** [comment]
@scrogson I just spent about an hour figuring this out for myself. I'm using Okta, which requires it for token requests. I wonder if there are providers which don't? Maybe this should be addressed in the README since this "comes up a lot".

**Comment by scrogson** [comment]
> Maybe this should be addressed in the README since this "comes up a lot".

A PR would be very welcome.
